### ISSUE TITLE
klipper

### ISSUE THREAD

**Issue by ckvsoft** [ModularPrintingSystem/IDM#13]
After a recent klipper update the shaper no longer works

mcu 'idm': Command format mismatch: query_lis2dw oid=%c rest_ticks=%u vs query_lis2dw oid=%c clock=%u rest_ticks=%u

**Comment by ModularPrintingSystem** [comment]
Did you also update the firmware for the IDM?

**Comment by ckvsoft** [comment]
Thanks @ModularPrintingSystem  for the quick reply

No, I couldn't find anywhere how to flash this to the USB version.

I went back to the initial 0.12 with Klipper
And I also have to use an earlier version of IDM. In the current IDM version there is another error. I would have to try it again after an update.

**Comment by ckvsoft** [comment]
> Did you also update the firmware for the IDM?

@ModularPrintingSystem 

Do you have a tip on how to update the IDM USB version? Or how do I switch to the correct mode for this? Quick unplugging/unplugging doesn't help

**Comment by ckvsoft** [comment]
@ModularPrintingSystem 

I found a way to flash the USB version. However, nothing works anymore. Before it was just the acceleration sensor. Now comes


Internal error during connect: invalid syntax (idm.py, line 888)

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

**Comment by ckvsoft** [comment]
Oh yes, the version of IDM is the same after the update. 2.0.0 is displayed

**Comment by ckvsoft** [comment]
I've fixed that now. Now works with the current klipper version.
It looks like you used a syntax that is only available from Python 3.10.
Klipper is Python2.

**Comment by ckvsoft** [comment]
@ModularPrintingSystem 
One more question. The firmware that is on the IDM scanner. Is there the source somewhere? Or is this plain klipper firmware?

**Comment by jackmiller1986** [comment]
what must i do that the idm works again with the new klipper usb version

**Comment by ModularPrintingSystem** [comment]
I updated the Readme, the problem should be solved.

**Comment by ckvsoft** [comment]
> what must i do that the idm works again with the new klipper usb version

@jackmiller1986 
It seems like this version assumes that Klipper has been patched to Python3. If you have a standard Klipper installation you can test my fork. It should work in both cases.

The firmware update in the USB variant cannot be switched off briefly and then switched to flash mode. There is also a description of this in my fork.
