### ISSUE TITLE
MCU protocol error

### ISSUE THREAD

**Issue by panik988** [ModularPrintingSystem/IDM#8]
Hello,
After updating Klipper I get this error:

mcu 'idm': Command format mismatch: query_lis2dw oid=%c rest_ticks=%u vs query_lis2dw oid=%c clock=%u rest_ticks=%u

If I comment the related Input Shaper cfg I can connect without problems but I am not able to make new vibration readings.

How can I solve it? Thank you

**Comment by NotTeoZz** [comment]
Same exact error, seems like one of the last klipper commit broke it :/

**Comment by ModularPrintingSystem** [comment]
This was a Firmware Bug, you can download the updated files.
