### ISSUE TITLE
At end of Bed_Mesh I have "Internal error on command:"BED_MESH_CALIBRATE"MCU Error after Full Update on Klipper

### ISSUE THREAD

**Issue by PopoTheBest** [ModularPrintingSystem/IDM#9]
Hello ,I have this error at the end of the Bed-Mesh process. This did not happen beofre I updated my Voron configuration. I'm on Klipper version v0.12.0-102-g9f41f53c. When I take a look at the Klippy.log, I see TypeError: __init__() takes exactly 3 arguments (2 given). I attached my log.
[klippy.log](https://github.com/ModularPrintingSystem/IDM/files/14114068/klippy.log)
Thanks in advance for helping.

**Comment by ModularPrintingSystem** [comment]
This was a Firmware Bug, you can download the updated files.

**Comment by PopoTheBest** [comment]
Ok, thank you !
